### ISSUE TITLE
source files not found

### ISSUE THREAD

**Issue by drorbemet** [Bruce-Connor/elisp-bug-hunter#11]
I installed elisp-bug-hunter in a prelude emacs config and tried to hunt bugs in prelude packages.
But bug-hunter-file and bug-hunter-init-file dont't find directories and package files.

How can I debug this? Which code is causing this, elisp-bug-hunter or https://github.com/bbatsov/prelude?

**Comment by Malabarba** [comment]
Could you be a little more specific? What is the is

**Comment by Malabarba** [comment]
Could you be a little more specific? Do you get some error when you run `M-x bug-hunter-file`?
You should be given a prompt where you can type in the file path, what do you mean by "don't find directories"?

**Comment by drorbemet** [comment]
1. `M-x bug-hunter-file`
2. select e.g. prelude-modules.el (because some of my modules seem to contain an error)
3. choose automatic error detection with e

#### _Bug Hunter Report_

Doing some initial tests...
Initial tests done. Hunting for the cause...
"/home/userprofile/.emacs.d/prelude-modules.el", line 6 pos 0:
  The following error was signaled here:
    (file-error "Cannot open load file" "file or folder was not found" "prelude-ido")
  Caused by the following expression:
    (require 'prelude-ido)

#### notes
- ~/.emacs.d is not a symlink
- ~/.emacs.d/modules/prelude-ido.el provides prelude-ido

**Comment by Malabarba** [comment]
Thanks, I think I understand now. What you want to do is not really supported yet.

When you bug-hunt a file, the file is loaded on top of an empty Emacs session. Therefore, if the file relies on something else having been loaded before it, then it's just going to fail.

This is not usually a problem with init files (which are always loaded on an empty emacs session), but it does get in the way of what you're trying to do.
