### ISSUE TITLE
Add descriptive terms for search engines like "bisect" and "debug"

### ISSUE THREAD

**Issue by alphapapa** [Bruce-Connor/elisp-bug-hunter#12]
I used this package several weeks ago, but just now when I needed to find it again, I couldn't find it with Google.  I searched for lots of things like "emacs debug init github", "emacs bisect init github", which you would think would bring it up...but none of them did.

When I finally found it again, I looked through the readme and saw that neither "bisect" nor "debug" are in the readme.  They really should be.  :)  "bisect init file" and "debug init file" ought to be in there as phrases, as well as "config" and ".emacs" and "init.el", etc.  I have a feeling that many people who could use this package aren't finding it.  :/

**Comment by Malabarba** [comment]
That's a good point. The readme needs a few search phrases. :+1:
