### ISSUE TITLE
What to do when hitting an unrelated issue when bisecting?

### ISSUE THREAD

**Issue by asmeurer** [Bruce-Connor/elisp-bug-hunter#14]
The instructions don't really say what to do when hitting an unrelated issue when bisecting, which is likely due to the nature of bisection (undefined variables and whatnot). I figured out, at least in my specific instance, that choosing `n` is the correct thing (otherwise it will just tell you what "causes" the unrelated issue, in my case, enabling some mode which defines a variable).

I also don't know if it's possible to implement a "skip" option like `git bisect` (I'm not really sure what exactly that would do).

**Comment by asmeurer** [comment]
This is in reference to interactive mode, in case that wasn't obvious.

**Comment by Malabarba** [comment]
Yeah, you did the right thing, and the instructions should say so.

It should be possible to implement a skip option, I would only need to know what it does. :-)
