### ISSUE TITLE
Interactive mode with terminal emacs

### ISSUE THREAD

**Issue by asmeurer** [Bruce-Connor/elisp-bug-hunter#15]
The interactive mode doesn't really work with the terminal emacs (emacs compiled with `--without-x`), because the new instance can't load in the same terminal.  Perhaps it could be made to work by starting a server and giving the user a command to connect to it with `emacsclient` in another terminal tab. At the very least, you might want to detect this and warn that it won't work.

**Comment by Malabarba** [comment]
Thanks for noticing this. I'll add some detection for this when I get a chance. :+1:

**Comment by Malabarba** [comment]
Speaking of it, does anyone know of a way to detect X support?

**Comment by asmeurer** [comment]
Is this what you are looking for https://emacs.stackexchange.com/questions/7151/is-there-a-way-to-detect-that-emacs-is-running-in-a-terminal? Or do you want to know if X is supported at all (even if the current session is started in `-nw` mode)?

**Comment by Malabarba** [comment]
I think just checking if we're in a terminal should be enough.
