### ISSUE TITLE
Assertion returns t in emacs -Q only in bug-hunter

### ISSUE THREAD

**Issue by fice-t** [Bruce-Connor/elisp-bug-hunter#16]
For some reason, when I try to do an assertion with the expression `(featurep 'tex-site)` I get the error:

```
Assertion returned non-nil even on emacs -Q:Remember, the assertion must be an expression that returns
non-nil in your current (problematic) Emacs state, AND that...
```

However, in an actual `emacs -Q` session `(featurep 'tex-site)` does actually return nil.

I can't seem to reproduce this with other features oddly enough. I'm not sure what's different here.

**Comment by Malabarba** [comment]
Thanks for reporting. I'll have a look at that when I get a chance.

**Comment by Malabarba** [comment]
Ok. When this happens, it probably means that the problem is happening inside `package-initialize`. I've chagned the failure message to reflect that. Sadly, we don't yet support bug-hunting inside package-initialize.
