### ISSUE TITLE
elisp-completion-at-point is not defined when pressing TAB

### ISSUE THREAD

**Issue by Wilfred** [Bruce-Connor/elisp-bug-hunter#17]
To reproduce: `M-x bug-hunter-init-file RET a TAB` produces in the minibuffer "completion--capf-wrapper: Symbol's function definition is void: elisp-completion-at-point".

Similarly, there's a byte-compile warning about `elisp-completion-at-point` not being defined.

Looking at the Emacs source code, this was added in 25.1. Earlier Emacsen use `lisp-completion-at-point`.

**Comment by Malabarba** [comment]
Cool. Thanks for catching that.
