### ISSUE TITLE
Unused lexical argument 'er'

### ISSUE THREAD

**Issue by fniessen** [Bruce-Connor/elisp-bug-hunter#18]
When installing bug-hunter from MELPA, just got the above warning.

Dunno if you wish to suppress it?

**Comment by Malabarba** [comment]
That's weird, I don't get that here. What's your Emacs version?

**Comment by fniessen** [comment]
Cygwin Emacs-w64 24.5.1 (of 2015-06-23).

Do you want a screenshot or something else to help?

Just tried to M-x byte-compile-file, and got it again. Warning on defun bug-hunter--read-buffer.

**Comment by Malabarba** [comment]
No need. I've just verified it here on 24.5 too. I'll think I'll just leave at that though. It's a false warning, and it no longer exists in Emacs 25 anyway.
Thanks for reporting. :+1:
