### ISSUE TITLE
Symbol's function definition is void: local

### ISSUE THREAD

**Issue by shymonk** [Bruce-Connor/elisp-bug-hunter#5]
Hi, firstly, great app! 
What's the meaning of `Symbol's function definition is void: local` when i issue M-x bug-hunter-init-file?

os: MacOS X
version: 24.3

**Comment by Malabarba** [comment]
Oh, it's a small bug of mine. I'll fix it now.

**Comment by Malabarba** [comment]
And BTW, Sorry I didn't see this before. I somehow didn't get notified about any of the issues in this repo.
