### ISSUE TITLE
just a thank you :)

### ISSUE THREAD

**Issue by zeltak** [Bruce-Connor/elisp-bug-hunter#6]
Hi!

just wanted to post a quick thank you for this life saver!

im a relatively neewb and always had to spend hours dissecting my config , using bug0unter solved my issues in 2 minutes!! amazing!
i really think this should be included in default emacs

thx again for this amazing addition to emacs

z

**Comment by Malabarba** [comment]
Thanks! A compliment is always appreciated!. :-)
