### ISSUE TITLE
bug-hunter fail on mac os x

### ISSUE THREAD

**Issue by matteo-l** [Bruce-Connor/elisp-bug-hunter#7]
Executing bug-hunter-init-file on mac os x 10.6 (snow leopard) fails with the message:

> Test failed.
> Detected a signaled error even on emacs -Q. I'm sorry, but there
> is something seriously wrong with your Emacs installation.
> There's nothing more I can do here.

Executing the function bug-hunter--run-form in the debugger I found that the execution of Emacs in batch mode fails with the error:

> Cannot open load file: no such file or directory, /var/folders/4q/4qVsrHdBERiEtwG6swW\+-k\+\+\+TI/-Tmp-/bug-hunter19558tbe

even if executing the same command from the shell works fine, with or without escaping the '+' characters.
If I remove the call to shell-quote-argument at line 233 everything works fine.

**Comment by Malabarba** [comment]
Hi there. I think this is fixed now (`shell-quote-arguments` is no longer being used).

Sorry I didn't see this before. I somehow didn't get notified about any of the issues in this repo.

**Comment by matteo-l** [comment]
It's not a problem, as I said I already found a workaround.
Thank you for your work.
