### ISSUE TITLE
elisp-bug-hunter uses the word 'frame' in a way that is inconsistent with its accepted definition

### ISSUE THREAD

**Issue by colonelpanic8** [Bruce-Connor/elisp-bug-hunter#9]
The definition I am referring to is
http://www.gnu.org/software/emacs/manual/html_node/emacs/Frames.html
The text I am referring to is contained in  `bug-hunter--interactive-explanation`
which has the following definition

``` elisp
(defconst bug-hunter--interactive-explanation
  "You have asked to do an interactive hunt, here's how it goes.
1) I will start a new Emacs frame.
2) You will try to reproduce your problem on the new frame.
3) When you’re done, close that frame.
4) I will ask you if you managed to reproduce the problem.
5) We will repeat steps up to %s times, so hang tight!")
```

Bug hunter is not really starting new frames, but entirely new emacs instances (which makes complete sense as a pristine lisp interpreter is needed to properly test the configuration). Saying that you are merely starting a new frame is confusing to users who understand the distinction between frames and instances and should probably be avoided

**Comment by Malabarba** [comment]
Thanks for reporting. Fixed!
